baseURL = 'https://babylonrpg.com/'
languageCode = 'en-us'
title = 'The Fall of Babylon'
theme = 'babylon-theme'

[params]
  description = "A dialectical materialist simulation game"
  featured_image = '/images/hero.jpg'
  
[module]
  [[module.mounts]]
    source = "static"
    target = "static"
